### ISSUE TITLE
Node.js 12 actions are deprecated. update the following actions to use Node.js 16: haythem/public-ip

### ISSUE THREAD

**Issue by carl-perry** [haythem/public-ip#18]
**Describe the bug**
Using this results in a warning related to the NodeJS version

_Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: haythem/public-ip_

**Comment by auberryberry** [comment]
I've raised a PR for this:
https://github.com/haythem/public-ip/pull/19
Alternatively, use my fork, until @haythem merges or fixes.

uses: betta-team/public-ip@master

**Comment by haythem** [comment]
Fixed by #19. I will also change the `::set-output` because of the upcoming deprecation mentioned in #20 before releasing the next version.

**Comment by haythem** [comment]
v1.3 is live. Thanks everyone.
