### ISSUE TITLE
Github will disable set-output.  Need to switch to using environment variable.

### ISSUE THREAD

**Issue by carl-perry** [haythem/public-ip#20]
**Describe the bug**
Github just started warning about set-output.  It will be disabled in the future.

**Warning**
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by cbrandborg** [comment]
It seems like it is only the `set-output ` command that will be deprecated. An alternative could just be to use the new syntax for the output parameter - See:  https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#setting-an-output-parameter

For instance I replaced my output command with the following and the deprecation warning went away (Sorry for slobby code): 

          GET_ARGO_STATUS=$(
                helm status argocd --namespace argocd --output json |
                grep -Po '"status": *\K"[^"]*"' |
                tr -d '"'
                ) 
          echo "ARGO-DEPLOYMENT-STATUS=$GET_ARGO_STATUS" >> $GITHUB_OUTPUT
          
          echo ${{ steps.argo-check.outputs.ARGO-DEPLOYMENT-STATUS }}

**Comment by haythem** [comment]
Hello @carl-perry, @cbrandborg,

Thanks for submitting this issue. I'll work on updating the code soon. I'll keep you posted.

**Comment by haythem** [comment]
@carl-perry,

Like @cbrandborg said, only the commands are impacted. For actions authors, only an update to the `@actions/core` package is needed (already done in #19).
