### ISSUE TITLE
https://api6.ipify.org/ does not resolve anymore (DNS_PROBE_FINISHED_NXDOMAIN)

### ISSUE THREAD

**Issue by artem-ego** [haythem/public-ip#4]
**Describe the bug**
The endpoint https://api6.ipify.org/ does not resolve and return DNS_PROBE_FINISHED_NXDOMAIN
So run action return error: 
Run haythem/public-ip@v1
Error: connect ENETUNREACH 2607:f2d8:4010:b::2:443 - Local (:::0)

**To Reproduce**
1. Run haythem/public-ip@v1

**Expected behavior**
Return the public IP address

**Additional context**
The configuration to select what IP version to fetch can do the trick

**Comment by haythem** [comment]
Hello @artem-ego,

Thanks for taking time to report the problem. Indeed, the ipify v6 endpoint has been deprecated as of today. A fix should be deployed by the end of the day (European Time).

**Comment by fjgal** [comment]
@haythem I went ahead and submitted a PR https://github.com/haythem/public-ip/pull/6

Thanks for this awesome action and quick turn around time!

**Comment by haythem** [comment]
@fjgal, your PR has been merged. Thanks again for your support.

Now you can use the v1.2 :100:

/cc @artem-ego

**Comment by TexasChainstoreManager** [comment]
Thanks for a quick fix, this saved my day!
